### ISSUE TITLE
Drag and drop

### ISSUE THREAD

**Issue by caroait** [radif/MSSticker-Images#1] opened 2016-07-26 22:08 UTC
I can't drag and drop the stickers those created with this library

**Comment by hsilived** [comment] 2016-08-02 18:00
I can confirm that using Xcode 8 beta 4 I can only drag the animated image the first time it loads (however the image won't "stick"). After that attempt I am not able to even drag the image any more.

**Comment by caroait** [comment] 2016-08-02 19:15
Now I have the same problem that @hsilived with Xcode 8 beta 4

**Comment by tomasdev** [comment] 2016-08-24 04:44
Any update on this? Or alternative you guys found?

**Comment by CharlesPanel** [comment] 2016-08-24 07:15
No alternative yet, the only code I can find for animated stickers on other forums all link back to this git.

**Comment by tomasdev** [comment] 2016-08-24 14:54
One alternative could be to pre-render the `apng` file and add it to the project, then use `Bundle.main...` to get its path like

``` swift
        let sticker = {
            let bundle = Bundle.main
            guard let placeholderURL = bundle.url(forResource: "animated_filename", withExtension: "png") else { fatalError("Unable to find sticker image") }

            do {
                let description = NSLocalizedString("A sticker", comment: "")
                return try MSSticker(contentsOfFileURL: placeholderURL, localizedDescription: description)
            }
            catch {
                fatalError("Failed to create sticker: \(error)")
            }
        }()
```

**Comment by hsilived** [comment] 2016-08-24 15:35
No Offense to radif, because I appreciate the efforts. I stopped using this library and was able to get animated stickers working natively in code. The real kicker for me was figuring out that in order to use the pre-generated apng's you reference them as a "png" in code not "apng". Hope this helps someone.

**Comment by tomasdev** [comment] 2016-08-24 16:11
@hsilived nice! do you have a sample piece of code you could share using that?

**Comment by hsilived** [comment] 2016-08-24 16:35
Here is my code, it is quite simple, I don't really do anything special for the animated stickers. The animated stickers I am using are "wtf" and "870194" in the list below.

```
class StickerBrowserViewController: MSStickerBrowserViewController {

    let stickerNames = ["piggie_cute", "piggie_bowing", "piggie_waving", "piggie_crying", "piggie_laughing", "piggie_winking", "professor_pig", "piggie_cheering", "piggie_scorning", "piggie_swooning", "wtf", "870194"]
    var stickers = [MSSticker]()
    weak var delegate: StickerBrowserViewControllerDelegate?

    override func viewDidLoad() {

        super.viewDidLoad()
        loadStickers()
    }

    override var stickerSize: MSStickerSize {
        get {
            return .regular
        }
    }

    func loadStickers() {

        stickers = stickerNames.map( {name in
            let url = Bundle.main.url(forResource: name, withExtension: "png")!
            return try! MSSticker(contentsOfFileURL: url, localizedDescription: name)
        })  
    }
}

extension StickerBrowserViewController {

    override func numberOfStickers(in stickerBrowserView: MSStickerBrowserView) -> Int {
        return stickers.count
    }

    override func stickerBrowserView(_ stickerBrowserView: MSStickerBrowserView, stickerAt index: Int) -> MSSticker {
        return stickers[index]
    }
}
```

**Comment by radif** [comment] 2016-08-24 16:50
The library creates stickers out of UIImage objects. The current limitation imposed by Apple is 500kb apng size and the image size varying 300x300 to 618-618 px. The stickers will not insert nor send if they don't match the criteria above. Use wisely. I will push an update checking parameters soon.

**Comment by hsilived** [comment] 2016-08-24 16:55
the issue wasn't whether or not the library would create an animated sticker from UIImages. It created the animated sticker just fine, I just couldn't drag it into the message window and get it to stick.

**Comment by radif** [comment] 2016-08-24 16:57
yes, invalid stickers will display, but won't "stick" afaik. I will update by returning an error or throwing

**Comment by radif** [comment] 2016-08-24 19:35
Fixed by throwing exceptions if the sticker is not matching Apple's criteria mentioned above.
To familarize yourself with the use case, see the example project, particularly, files: ExampleCollectionViewCell.swift, MessagesViewController.swift, StickerData.swift

```
let sticker :MSSticker
do {
try sticker=MSSticker(images: images, format: .apng, frameDelay: 1.0/14.0, numberOfLoops: 0, localizedDescription: localizedDescription)

}catch MSStickerAnimationInputError.InvalidDimensions {
try! sticker=MSSticker(contentsOfFileURL:  urlForImageName("invalid_image_size"), localizedDescription: "invalid dimensions")

}catch MSStickerAnimationInputError.InvalidStickerFileSize {
try! sticker=MSSticker(contentsOfFileURL: urlForImageName("invalid_file_size"), localizedDescription: "invalid file size")

} catch { fatalError("other error:\(error)") }
```

**Closed as completed by radif** 2016-08-24 19:35 UTC
